# Generated by Django 4.2.7 on 2023-12-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='resipient',
            new_name='recipient',
        ),
    ]
