# Generated by Django 4.2.7 on 2023-12-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_rename_resipient_message_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
