# Generated by Django 4.2.7 on 2023-12-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='web_app_model_id',
        ),
    ]
