# Generated by Django 4.2.7 on 2023-12-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_rename_post_like_web_app_model_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='web_app_model_id',
            new_name='web_app_model',
        ),
    ]
