# Generated by Django 4.2.7 on 2023-12-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_rename_web_app_model_id_like_web_app_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='web_app_model',
            new_name='post',
        ),
    ]
